    // 국내 추천 이미지 list
    let arr_domestic_list = ['Gapyung','Gangneung','Gyeongju','Busan','Seoul','Sokcho','Yeosu','Incheon','Jejudo']
    let arr_domestic_korean = ['가평','강릉','경주','부산','서울','속초','여수','인천','제주도']
    // 해외 이미지 리스트
    let arr_oversea_list = ['Guam','Natlang','Danang','Dokyo','Bangkuk','Singgapol','Osaka','Cotakinablue','Kyoto']
    let arr_oversea_koean = ['괌','나트랑','다낭','도쿄','방콕','싱가폴','오사카','코타키나블루','쿄토']

    let arr_domestic_list_All = ['Gapyung','Gangneung','Gyeongju','Busan','Seoul','Sokcho','Yeosu','Incheon','Jejudo','Guam','Natlang','Danang','Dokyo','Bangkuk','Singgapol','Osaka','Cotakinablue','Kyoto']
    let arr_domestic_korean_All = ['가평','강릉','경주','부산','서울','속초','여수','인천','제주도','괌','나트랑','다낭','도쿄','방콕','싱가폴','오사카','코타키나블루','쿄토']


    let event_list = [
        [{event_idx:'0',src:'광고0.jpg', summery:'4월 국내 숙소 쿠폰팩',date:'24.04.01~24.04.30 23:59'},
        {event_idx:'1',src:'광고1.jpg', summery:'4해외여행 황금연휴 쿠폰팩',date:'24.04.01~24.04.30 23:59'},
        {event_idx:'2',src:'광고2.jpg', summery:'위클리 오픈런',date:'24.04.01~24.04.30 23:59'},
        {event_idx:'3',src:'광고3.jpg', summery:'4베스트 호텔딜',date:'24.04.01~24.04.03 23:59'},
        {event_idx:'4',src:'광고4.jpg', summery:'더블쿠폰 핫세일',date:'24.04.01~24.04.10 23:59'},
        {event_idx:'5',src:'광고5.jpg', summery:'반려견 블랙어때',date:'24.04.01~24.04.30 23:59'},
        {event_idx:'6',src:'광고6.jpg', summery:'인기공간 할인파티',date:'24.04.01~24.04.30 23:59'},
        {event_idx:'7',src:'광고7.jpg', summery:'4월 신규회원 웰컴 쿠폰',date:'24.04.01~24.04.30 23:59'},
        {event_idx:'8',src:'광고8.jpg', summery:'24년 4월 결제 프로모션 모음',date:'24.04.01~24.04.30 23:59'},
        ],
        [{event_idx:'0',src:'광고모텔0.webp', summery:'4월 국내숙소 쿠폰팩',date:'24.04.01~24.04.30 23:59'}
        ],
        [{event_idx:'0',src:'광고_호텔리조트0.webp', summery:'4월 국내숙소 쿠폰팩',date:'24.04.01~24.04.30 23:59'},
        {event_idx:'1',src:'광고_호텔리조트1.webp', summery:'선착순 더블 할인 호텔',date:'24.04.01~24.04.10 23:59'}
        ],
        [{event_idx:'0',src:'광고_팬션0.webp', summery:'4월 국내숙소 쿠폰팩',date:'24.04.01~24.04.30 23:59'},
        {event_idx:'1',src:'광고_팬션1.webp', summery:'선착순 더블 할인 펜션',date:'24.04.01~24.04.10 23:59'}
        ],
        [{event_idx:'0',src:'광고_해외0.webp', summery:'해외여행 황금 연휴 쿠폰팩',date:'24.04.01~24.04.30 23:59'},
        ]
    ]

    let event_nm = [
        'HOT','모텔','호텔·리조트','펜션·캠핑·게하','해외여행'
    ]

    let dicObject_1 = [[
        {}
    ]

    ]

let dicObject = {}
dicObject['gapyung'] = [

    {'type_en':'Camping',
    'type':'캠핑','name':'가평 디프라이빗 캠핑','address':'가평군 용소폭포','star':'9.8','person':'112','price':'129000'},
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'가평 디파우제풀빌라스파펜션',
    'address':'가평군 가평수목원',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'가평 더상상풀빌라 글램핑',
    'address':'가평군 자라섬',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'가평 아란풀빌라',
    'address':'가평군 쁘띠프랑스',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'가평 오리온 독채 풀빌라',
    'address':'가평군 용소폭포',
    'star':'9.8',
    'person':'112',
    'price':'12000'},

    {'type_en':'Pansion',
    'type':'팬션',
    'name':'가평 도우',
    'address':'가평군 용소폭포',
    'star':'9.8',
    'person':'112',
    'price':'129'},

    {'type_en':'Camping',
    'type':'캠핑',
    'name':'가평호명나루165풀빌라',
    'address':'가평군 용소폭포',
    'star':'9.8',
    'person':'112',
    'price':'29000'},

    {'type_en':'Camping',
    'type':'캠핑',
    'name':'가평 더쉼 풀빌라',
    'address':'가평군 용소폭포',
    'star':'9.8',
    'person':'112',
    'price':'12900'},

    {'type_en':'Camping',
    'type':'캠핑',
    'name':'남이성 더 휴 스파펜션',
    'address':'가평군 용소폭포',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]

// 강릉
dicObject['Gangneung'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'세인트존스호텔',
    'address':'강릉시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'스카이베이경포',
    'address':'강릉시 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    {'type_en':'Motel',
    'type':'모텔',
    'name':'썬크루즈호텔',
    'address':'강릉시 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'리카이 샌드파인',
    'address':'강릉시 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'H9스파펜션',
    'address':'강릉시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'웨이플루',
    'address':'강릉시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    {'type_en':'Motel',
    'type':'모텔',
    'name':'더강릉오션스테이',
    'address':'강릉시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'블리스가족펜션',
    'address':'강릉시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'오션힐펜션',
    'address':'강릉시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]

// 경주
dicObject['Gyeongju'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'힐튼경주',
    'address':'경주시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'라한셀렉트',
    'address':'경주시 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    {'type_en':'Motel',
    'type':'모텔',
    'name':'베스트웨스턴플러스',
    'address':'경주시 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'트라제풀빌라',
    'address':'경주시 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'블루원',
    'address':'경주시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'JI스테이',
    'address':'경주시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    {'type_en':'Motel',
    'type':'모텔',
    'name':'이제',
    'address':'경주시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'더테라스',
    'address':'경주시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'로즈브리즈',
    'address':'경주시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]



// 'Busan'
dicObject['Busan'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'엘모멘토',
    'address':'부산시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},

    {'type_en':'Pansion',
    'type':'팬션',
    'name':'동백호텔',
    'address':'부산시 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},

    {'type_en':'Motel',
    'type':'모텔',
    'name':'메종드센텀',
    'address':'부산시 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},

    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'호텔1',
    'address':'부산시 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},

    {'type_en':'Camping',
    'type':'캠핑',
    'name':'어반스테이',
    'address':'부산시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},

    {'type_en':'Pansion',
    'type':'팬션',
    'name':'W레지던스',
    'address':'부산시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},

    {'type_en':'Motel',
    'type':'모텔',
    'name':'센트럴베이광안리',
    'address':'부산시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},

    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'래디언트 남포',
    'address':'부산시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},

    {'type_en':'Camping',
    'type':'캠핑',
    'name':'아쿠아팰리스',
    'address':'부산시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]


//,'Seoul'
dicObject['Seoul'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'서울신라호텔',
    'address':'서울시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},

    {'type_en':'Pansion',
    'type':'팬션',
    'name':'종로 부티크 호텔',
    'address':'서울시 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},

    {'type_en':'Motel',
    'type':'모텔',
    'name':'길동 MARI-마리',
    'address':'서울시 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},

    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'라뉘호텔',
    'address':'서울시 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},

    {'type_en':'Camping',
    'type':'캠핑',
    'name':'솔라고 명동 호텔',
    'address':'서울시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},

    {'type_en':'Pansion',
    'type':'팬션',
    'name':'사당 호텔 카일',
    'address':'서울시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},

    {'type_en':'Motel',
    'type':'모텔',
    'name':'역삼 인트로호텔',
    'address':'서울시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},

    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'더 디자이너스 프리미어',
    'address':'서울시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},

    {'type_en':'Camping',
    'type':'캠핑',
    'name':'바론드 호텔',
    'address':'서울시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]




//,'Sokcho'
dicObject["Sokcho"] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'아이파크스위트',
    'address':'속초시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'어반스테이 속초등대',
    'address':'속초시 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'속초해오름',
    'address':'속초시 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'채스터톤스',
    'address':'속초시 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'라마다 속초',
    'address':'속초시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'속초 아이파크 스위트호텔',
    'address':'속초시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'씨크루즈호텔 속초',
    'address':'속초시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'뉴욕카라반 속초',
    'address':'속초시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'마리나베이 속초',
    'address':'속초시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]


// ,'Yeosu'
dicObject["Yeosu"]=[
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'신라스테이 여수',
    'address':'여수시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'여수 라마다 프라자 호텔',
    'address':'여수시 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'여수 오션힐호텔',
    'address':'여수시 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'헤이븐 호텔',
    'address':'여수시 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'르파라디 오션뷰스',
    'address':'여수시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'디아크 리조트',
    'address':'여수시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'라온피네스파멘션',
    'address':'여수시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'여수 베네치아호텔',
    'address':'여수시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'코업스테이 여수',
    'address':'여수시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]



// ,'Incheon'
dicObject["Incheon"] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'구월 호텔반월',
    'address':'인천시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'구월도 구월호텔',
    'address':'인천시 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    {'type_en':'Motel',
    'type':'모텔',
    'name':'네스트호텔 인천',
    'address':'인천시 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'부평 스테이 인 호텔',
    'address':'인천시 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'인청공항 디케이',
    'address':'인천시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'영종 웨스턴 그레이스',
    'address':'인천시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    {'type_en':'Motel',
    'type':'모텔',
    'name':'구월 호텔 더 디자이너스',
    'address':'인천시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'부평 더휴식 아늑호텔',
    'address':'인천시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'서구 저스트슬립호텔',
    'address':'인천시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]



//,'Jejudo',
dicObject["Jejudo"] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'제주신라호텔',
    'address':'제주도 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'롯데호텔 제주',
    'address':'제주도 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'랜딩관 제주신화월드 호텔',
    'address':'제주도 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'노블피아호텔',
    'address':'제주도 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'서귀포 타마라호텔',
    'address':'제주도 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'호텔 원스토리',
    'address':'제주도 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'제주 아루미호텔',
    'address':'제주도 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'제주 더포그레이스 호텔',
    'address':'제주도 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'라마다 제주시티',
    'address':'제주도 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]





//'Guam',
dicObject["Guam"] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'두짓타니 괌 리조트',
    'address':'괌 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'더 츠바키 타워',
    'address':'괌 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'롯데 호텔 괌',
    'address':'괌 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'괌 리프 호텔',
    'address':'괌 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'괌 플라자 리조트 앤 스파',
    'address':'괌 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'로얄 오키드 괌',
    'address':'괌 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'호텔 타노 괌',
    'address':'괌 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'크라운 플라자 리조트',
    'address':'괌 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'레오팰리스 리조트',
    'address':'경주시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000',}
]



//'Natlang'
dicObject['Natlang'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'리게일리어 골드 호텔',
    'address':'나트랑 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'버고 호텔',
    'address':'나트랑 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'엘마 리조트 깜라인',
    'address':'나트랑 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'르모어 호텔 나트랑',
    'address':'나트랑 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'아미아나 리조트',
    'address':'나트랑 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'디셈버 호텔',
    'address':'나트랑 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'보마 리조트 나트랑',
    'address':'나트랑 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'더 아남',
    'address':'나트랑 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'모조 인',
    'address':'나트랑 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]


//,'Danang',

dicObject['Danang'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'골든 로터스',
    'address':'다낭 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'치 하우스 다낭',
    'address':'다낭 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'모나크 호텔 다낭',
    'address':'다낭 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'베이 캐피탈 다낭',
    'address':'다낭 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'뉴 오리엔트 호텔 다낭',
    'address':'다낭 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'신라 모노그램 꽝남 다낭',
    'address':'다낭 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'골든 로터스 그랜드 다낭',
    'address':'다낭 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'스텔라 마리스 비치 다낭',
    'address':'다낭 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'르 센스 오션 프론트 다낭',
    'address':'다낭 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
]


//'Dokyo',
dicObject['Dokyo'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'호텔 몬토레 라 스루 긴자',
    'address':'도쿄 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'렘 롯폰기',
    'address':'도쿄 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'호텔 몬토레 한조몬',
    'address':'도쿄 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'호텔 오리엔탈 익스프레스 도쿄',
    'address':'도쿄 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'긴자 캐피탈 호텔',
    'address':'도쿄 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'호텔 몬토레 긴자',
    'address':'도쿄 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'APA 호텔 니혼바시',
    'address':'도쿄 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'호텔 먼데이 프리미엄',
    'address':'도쿄 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'수퍼 호텔 로하스 이케무쿠로',
    'address':'도쿄 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]



//'Bangkuk',
dicObject['Bangkuk'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'차트리움 그랜드 방콕',
    'address':'방콕 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'신돈 켐핀스키 호텔',
    'address':'방콕 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'베스트웨스턴플러스',
    'address':'방콕 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'더 스탠다드 방콕',
    'address':'방콕 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'코모 메트로폴리탄 방콕',
    'address':'방콕 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'시안 켐핀스키 호텔',
    'address':'방콕 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'아바니 플러스 리버사이드 방콕',
    'address':'방콕 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'그랜드 센터 포인트 수쿰빗 55통로',
    'address':'방콕 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'이비스 스타일스 방콕',
    'address':'방콕 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]



//'Singgapol',
dicObject['Singgapol'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'더 풀러턴 호텔',
    'address':'싱가폴 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'빌리지 호텔 센토사 바이 퍼 이스트',
    'address':'싱가폴 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'파크로얄 컬렉션 픽커링',
    'address':'싱가폴 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'요텔 싱가포르 오차드',
    'address':'싱가폴 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'카프리 바이 프레이저 차이나',
    'address':'싱가폴 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'칼튼 시티 호텔 싱가포르',
    'address':'싱가폴 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'스위소텔 더 스탬포드',
    'address':'싱가폴 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'30 벤쿨렌',
    'address':'싱가폴 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'파크 레지스 싱가포르',
    'address':'싱가폴 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]



//'Osaka',
dicObject['Osaka'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'프리미어 호텔 캐빈',
    'address':'오사카 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'소테츠 그랜드 프레사 오사카',
    'address':'오사카 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'호텔 한큐 리스파이어 오사카',
    'address':'오사카 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'칸데오 호텔 오사카',
    'address':'오사카 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'레드 루프 인 앤 스위트 오사카',
    'address':'오사카 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'호텔 몬토레 라 스루 오사카',
    'address':'오사카 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'호텔 케이한 난바',
    'address':'오사카 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'호텔 몬토레 오사카',
    'address':'오사카 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'일쿠오레 난바',
    'address':'오사카 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]



//'Cotakinablue'
dicObject['Cotakinablue'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'샹그릴라 탄중아루 코타키나발루',
    'address':'코타키나발루 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'호텔 7 수리아',
    'address':'코타키나발루 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'넥서스 리조트 앤 스파 카람부나이',
    'address':'코타키나발루 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'힐튼 코타키나발루',
    'address':'코타키나발루 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'더 루마 호텔',
    'address':'코타키나발루 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'홀리데이 인 익스프레스 코타키나발루',
    'address':'코타키나발루 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'홀리데이 인 익스프레스 코타키나발루 시티센터',
    'address':'코타키나발루 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'스탠턴 호텔',
    'address':'코타키나발루 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'AC 레지던스',
    'address':'코타키나발루 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]


//,'Kyoto'
dicObject['Kyoto'] = [
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'호텔 몬토레 교토',
    'address':'교토시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'리치몬드 호텔 프리미어 교토',
    'address':'교토시 어딘가..',
    'star':'9.6',
    'person':'81',
    'price':'42100'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'오리엔탈 호텔 교토 로쿠조',
    'address':'교토시 어딘가..',
    'star':'9.7',
    'person':'98',
    'price':'79000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'호텔 비나리오 사가 아리사마야',
    'address':'교토시 어딘가..',
    'star':'9.9',
    'person':'114',
    'price':'170000'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'아라시야마 온천 가덴쇼',
    'address':'교토시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'},
    
    {'type_en':'Pansion',
    'type':'팬션',
    'name':'호텔 그레이서리 교토 산조',
    'address':'교토시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'129'},
    
    {'type_en':'Motel',
    'type':'모텔',
    'name':'미츠이 가든 호텔',
    'address':'교토시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'29000'},
    
    {'type_en':'Fullbilla',
    'type':'풀빌라',
    'name':'호텔 칸라 교토',
    'address':'교토시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12900'},
    
    {'type_en':'Camping',
    'type':'캠핑',
    'name':'랜더 레지던셜 호텔 교토',
    'address':'교토시 어딘가..',
    'star':'9.8',
    'person':'112',
    'price':'12000'}
]


